[build]
command = "./build.sh"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.139.4"
GO_VERSION = "1.23.3"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.134.2"
GO_VERSION = "1.23.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.134.2"
GO_VERSION = "1.23.1"

[context.branch-deploy.environment]
HUGO_VERSION = "0.134.2"
GO_VERSION = "1.23.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

